### ISSUE TITLE
Request the model for grayscale deblurring

### ISSUE THREAD

**Issue by ysnan** [siavashBigdeli/DMSP-tensorflow#1]
I find that the model provided for non-blind deblur is suitable for RGB images. Could you please provide the model and code suitable for grayscale deblur as Figure 3 in your paper? This is helpful for comparison with other classical methods. 
Thank you!

**Comment by siavashBigdeli** [comment]
The model is trained on both RGB and grayscale images; you just need to replicate your grayscale image and average the output each time you use the model.

**Comment by ysnan** [comment]
I have already done like this. Thank you for your comments.
