### ISSUE TITLE
Add code license

### ISSUE THREAD

**Issue by HedgehogCode** [siavashBigdeli/DMSP-tensorflow#2]
Code without a license is under exclusive copyright by default which prevents people from using your code. See https://choosealicense.com/no-permission/.

If this is intended it would make sense to add a short notice to the `README.md` to avoid confusion.

If this is not intended it would be awesome if you could add a license. https://choosealicense.com/ can help you to choose a license.

**Comment by siavashBigdeli** [comment]
Thanks for the hint!
