### ISSUE TITLE
Iteration time is about 192 seconds

### ISSUE THREAD

**Issue by cxzhou95** [siavashBigdeli/DMSP-tensorflow#3]
Hello, siavashBigdeli.
I am using Python2.7 and Tensorflow 1.12.
When I run demo_DMSP, it takes about 192s for each iteration. My degrade image size is 1200x1920, blur kernel is 71x71, Is this iteration time normal? Thank you!

**Comment by siavashBigdeli** [comment]
Hi there 
I cannot tell since I never tried with a kernel of 71x71. However your image resolution is also very high so it is certainly possible. Are you sure that you have your GPU activated for the neural net?

**Comment by cxzhou95** [comment]
> Hi there
> I cannot tell since I never tried with a kernel of 71x71. However your image resolution is also very high so it is certainly possible. Are you sure that you have your GPU activated for the neural net?

Yes. The GPU is used. I think it is because of the 'filter_image' and 'convolution_image' taking much time since the kernel and image resolution both are very high. Thank you for your reply!

**Comment by siavashBigdeli** [comment]
have a look at this:
https://github.com/DawyD/cnn-map-denoiser
Since kernel operations are done in frequency domain, it is much faster.
